export type CoreFeature = {
  id: number;
  name: string;
  group: string;
};

type FeatureGroup = {
  group: string;
  features: string[];
};

const featureGroups: FeatureGroup[] = [
  {
    group: "Chat Workspace",
    features: [
      "Full-page chat workspace",
      "Chat sidebar",
      "New chat button",
      "Rename chats",
      "Delete chats",
      "Search chats",
      "Pin chats",
      "Archive chats",
      "Chat folders",
      "Favorite chats",
    ],
  },
  {
    group: "Message UX",
    features: [
      "Message copy button",
      "Message edit button",
      "Regenerate response",
      "Continue response",
      "Stop generating button",
      "Typing animation",
      "Clean thinking indicator",
      "Hidden tool usage",
      "Clean final answers",
      "Markdown rendering",
    ],
  },
  {
    group: "Code Files Images Data",
    features: [
      "Code block rendering",
      "Code copy button",
      "File download button",
      "Image preview in chat",
      "Image generation in chat",
      "Image download button",
      "Uploaded image analysis",
      "Drag-and-drop uploads",
      "Multi-file uploads",
      "PDF reading roadmap",
      "CSV/table analysis",
      "JSON analysis",
      "Text file analysis",
      "Screenshot error reading",
    ],
  },
  {
    group: "Memory",
    features: [
      "Conversation memory",
      "Long-term admin memory",
      "Memory manager page",
      "Delete memory items",
      "Memory search",
      "Saved instructions",
      "Chat history synced to Supabase",
      "Auto-summarized chat memory",
      "Memory freshness checks",
      "Private memory safety rules",
    ],
  },
  {
    group: "Personality Voice Mobile",
    features: [
      "Custom assistant personality",
      "Admin tone preferences",
      "Slang/typo understanding",
      "Multilingual replies",
      "Mobile-friendly chat UI",
      "Fixed bottom composer",
      "ChatGPT-style composer",
      "Attach button",
    ],
  },
  {
    group: "Prompts Actions Export",
    features: [
      "Prompt suggestions",
      "Saved prompt templates",
      "Prompt library",
      "Recent prompts",
      "One-click admin actions",
      "Tool action buttons",
      "Website scan button",
      "Database scan button",
      "Project search button",
      "Web research button",
      "Image generate button",
      "File generate button",
      "Report generate button",
      "Export chat as Markdown",
      "Export chat as TXT",
    ],
  },
  {
    group: "Security Trust Storage Knowledge",
    features: [
      "Private admin-only chats",
      "Role-based access",
      "Owner-only settings",
      "Generated images saved safely without localStorage crashes",
      "Knowledge base upload",
      "Knowledge search",
      "Repo file index",
      "Supabase schema index",
      "Admin data index",
      "Minecraft server knowledge index",
      "Tool result citations hidden by default",
      "Better hallucination guard",
      "Honest I-don't-know fallback",
      "Clarifying question mode",
    ],
  },
  {
    group: "Assistant Modes",
    features: [
      "Code assistant behavior",
      "Data analyst behavior",
      "Minecraft admin behavior",
      "Store manager behavior",
      "Security auditor behavior",
      "Debugger behavior",
      "Task planner behavior",
      "Report writer behavior",
      "SQL assistant behavior",
      "Product builder behavior",
    ],
  },
  {
    group: "Minecraft Store Cloudflare",
    features: [
      "RCON command assistant",
      "Live server status tool",
      "Live player list tool",
      "Checkout troubleshooting tool",
      "Order investigation tool",
      "Cloudflare deploy debugging tool",
      "Cloudflare Workers AI response fallback",
      "Cloudflare asset/MIME troubleshooting",
      "SPA routing checker",
      "Pages environment variable checklist",
    ],
  },
  {
    group: "Core Reliability",
    features: [
      "Core model status checker",
      "AI response quality tester",
      "Hallucination detection checklist",
      "Prompt injection guard",
      "Secret leak scanner",
      "Admin session validator",
      "Login issue debugger",
      "Password reset flow tester",
      "Email verification flow tester",
      "Auth redirect checker",
    ],
  },
  {
    group: "Checkout And Orders",
    features: [
      "Checkout step-by-step debugger",
      "Payment amount mismatch detector",
      "Cart total recalculator",
      "Promo stacking rule checker",
      "Tax/fee calculator",
      "Order timeline viewer",
      "Delivery retry button",
      "Delivery queue monitor",
      "Pending order priority sorter",
      "Manual delivery assistant",
    ],
  },
  {
    group: "Product Admin",
    features: [
      "Product import from CSV",
      "Product export to CSV",
      "Bulk product editor",
      "Bulk price updater",
      "Rank perk formatter",
      "Command syntax validator",
      "LuckPerms permission checker",
      "Crate reward table builder",
      "Cosmetic category manager",
      "Store homepage section builder",
    ],
  },
  {
    group: "Content Marketing",
    features: [
      "Announcement banner manager",
      "Maintenance mode helper",
      "Changelog generator",
      "Patch notes writer",
      "Discord embed generator",
      "TikTok caption generator",
      "YouTube description generator",
      "Facebook post generator",
      "Store FAQ generator",
      "Help center article generator",
      "Terms of service generator",
      "Privacy policy generator",
      "Refund policy generator",
      "Staff application form builder",
      "Appeal form builder",
      "Bug report form builder",
      "Suggestion form builder",
    ],
  },
  {
    group: "Admin Dashboard Analytics",
    features: [
      "Admin dashboard widget builder",
      "Revenue chart builder",
      "Product popularity chart",
      "Conversion funnel report",
      "Abandoned cart tracker",
      "Returning customer report",
      "New player report",
      "Top spender report",
      "Promo effectiveness report",
      "Failed checkout report",
      "RCON failure report",
      "Server uptime report",
      "Admin activity report",
    ],
  },
  {
    group: "Project Knowledge And Dev Tools",
    features: [
      "Knowledge base versioning",
      "Knowledge source citations",
      "Knowledge freshness checker",
      "Repo index rebuild button",
      "File diff viewer",
      "Code change proposal viewer",
      "Safe patch approval flow",
      "Git status viewer",
      "Git diff explainer",
      "Commit message generator",
      "Release checklist generator",
      "Cloudflare preview deploy helper",
      "Environment variable checklist",
      "Wrangler config checker",
      "Headers/redirects checker",
      "Asset cache rules checker",
    ],
  },
  {
    group: "SEO Performance Accessibility",
    features: [
      "SEO metadata checker",
      "Sitemap generator",
      "Robots.txt checker",
      "OpenGraph image generator",
      "Mobile layout checker",
      "Accessibility checker",
      "Color contrast checker",
      "Broken image detector",
      "Broken link detector",
      "Console error collector",
      "Performance budget checker",
      "Bundle split suggestion tool",
      "Lazy loading suggestion tool",
    ],
  },
  {
    group: "Recovery Accounts Players",
    features: [
      "Admin onboarding guide",
      "Owner-only recovery guide",
      "Emergency lockdown mode",
      "Backup restore guide",
      "Database cleanup assistant",
      "Storage cleanup assistant",
      "Duplicate account merge helper",
      "Player purchase history viewer",
      "Player rank history viewer",
      "Player support timeline",
      "What should I do next smart planner",
    ],
  },
  {
    group: "Operator Workflow",
    features: [
      "Core command palette",
      "Keyboard shortcuts",
      "Split-screen answer/code viewer",
      "Scratchpad notes",
      "Task checklist tracker",
      "Admin SOP generator",
      "Store launch checklist",
      "Rank balancing advisor",
      "Economy balancing advisor",
    ],
  },
  {
    group: "Server Growth",
    features: [
      "Server event planner",
      "Seasonal sale planner",
      "A/B pricing experiment planner",
      "Coupon campaign planner",
      "Customer segmentation helper",
      "Player retention report",
      "Churn risk detector",
      "Staff performance notes",
      "Support ticket triage",
      "Complaint sentiment analyzer",
    ],
  },
  {
    group: "Moderation QA",
    features: [
      "Toxic message filter ideas",
      "Chat moderation rule helper",
      "Ban appeal analyzer",
      "Whitelist application reviewer",
      "Bug reproduction steps generator",
      "QA test case generator",
      "Regression checklist",
      "Browser compatibility checker",
      "Device preview checklist",
      "PWA install helper",
    ],
  },
  {
    group: "Notifications Incidents Delivery",
    features: [
      "iPhone home-screen guide",
      "Offline admin fallback page",
      "Admin notification inbox",
      "Incident report generator",
      "Status page writer",
      "Maintenance announcement scheduler",
      "RCON retry policy builder",
      "Delivery rollback command builder",
      "Player compensation calculator",
      "Rank upgrade price calculator",
    ],
  },
  {
    group: "Brand And Store Intelligence",
    features: [
      "Bundle discount optimizer",
      "Item naming convention checker",
      "Slug collision checker",
      "Product image prompt library",
      "Brand style guide generator",
      "Lunaris lore/copywriter",
      "Landing page hero generator",
      "Email subject line generator",
      "Admin weekly digest",
      "Core self-test suite",
    ],
  },
];

export const coreFeatureRegistry: CoreFeature[] = featureGroups.flatMap((group) => group.features).map((name, index) => {
  const group = featureGroups.find((item) => item.features.includes(name));
  return {
    id: index + 1,
    group: group?.group || "Core",
    name,
  };
});

export function renderCoreFeatureRegistry() {
  return featureGroups
    .map((group) => {
      const features = coreFeatureRegistry.filter((feature) => feature.group === group.group);
      return [`${group.group}`, ...features.map((feature) => `${feature.id}. ${feature.name}`)].join("\n");
    })
    .join("\n\n");
}
