export type CoreFeature = {
  id: number;
  name: string;
  group: string;
};

export const coreFeatureRegistry: CoreFeature[] = [
  { id: 1, group: "Chat Workspace", name: "Full-page chat workspace" },
  { id: 2, group: "Chat Workspace", name: "Chat sidebar" },
  { id: 3, group: "Chat Workspace", name: "New chat button" },
  { id: 4, group: "Chat Workspace", name: "Rename chats" },
  { id: 5, group: "Chat Workspace", name: "Delete chats" },
  { id: 6, group: "Chat Workspace", name: "Search chats" },
  { id: 7, group: "Chat Workspace", name: "Pin chats" },
  { id: 8, group: "Chat Workspace", name: "Archive chats" },
  { id: 9, group: "Chat Workspace", name: "Chat folders" },
  { id: 10, group: "Chat Workspace", name: "Favorite chats" },
  { id: 11, group: "Message UX", name: "Message copy button" },
  { id: 12, group: "Message UX", name: "Message edit button" },
  { id: 13, group: "Message UX", name: "Regenerate response" },
  { id: 14, group: "Message UX", name: "Continue response" },
  { id: 15, group: "Message UX", name: "Stop generating button" },
  { id: 16, group: "Message UX", name: "Typing animation" },
  { id: 17, group: "Message UX", name: "Thinking indicator" },
  { id: 18, group: "Message UX", name: "Hidden tool usage" },
  { id: 19, group: "Message UX", name: "Clean final answers" },
  { id: 20, group: "Message UX", name: "Markdown rendering" },
  { id: 21, group: "Code", name: "Code block rendering" },
  { id: 22, group: "Code", name: "Code copy button" },
  { id: 23, group: "Files", name: "File download button" },
  { id: 24, group: "Images", name: "Image preview in chat" },
  { id: 25, group: "Images", name: "Image generation in chat" },
  { id: 26, group: "Images", name: "Image download button" },
  { id: 27, group: "Images", name: "Uploaded image analysis" },
  { id: 28, group: "Files", name: "Drag-and-drop uploads" },
  { id: 29, group: "Files", name: "Multi-file uploads" },
  { id: 30, group: "Files", name: "PDF reading" },
  { id: 31, group: "Data", name: "CSV/table analysis" },
  { id: 32, group: "Data", name: "JSON analysis" },
  { id: 33, group: "Files", name: "Text file analysis" },
  { id: 34, group: "Images", name: "Screenshot error reading" },
  { id: 35, group: "Memory", name: "Conversation memory" },
  { id: 36, group: "Memory", name: "Long-term admin memory" },
  { id: 37, group: "Memory", name: "Memory manager page" },
  { id: 38, group: "Memory", name: "Delete memory items" },
  { id: 39, group: "Memory", name: "Memory search" },
  { id: 40, group: "Memory", name: "Saved instructions" },
  { id: 41, group: "Personality", name: "Custom assistant personality" },
  { id: 42, group: "Personality", name: "Admin tone preferences" },
  { id: 43, group: "Personality", name: "Slang/typo understanding" },
  { id: 44, group: "Personality", name: "Multilingual replies" },
  { id: 45, group: "Voice", name: "Voice input" },
  { id: 46, group: "Voice", name: "Voice output" },
  { id: 47, group: "Mobile", name: "Mobile-friendly chat UI" },
  { id: 48, group: "Composer", name: "Fixed bottom composer" },
  { id: 49, group: "Composer", name: "ChatGPT-style composer" },
  { id: 50, group: "Composer", name: "Attach button" },
  { id: 51, group: "Prompts", name: "Prompt suggestions" },
  { id: 52, group: "Prompts", name: "Saved prompt templates" },
  { id: 53, group: "Prompts", name: "Prompt library" },
  { id: 54, group: "Prompts", name: "Recent prompts" },
  { id: 55, group: "Actions", name: "One-click admin actions" },
  { id: 56, group: "Actions", name: "Tool action buttons" },
  { id: 57, group: "Actions", name: "Website scan button" },
  { id: 58, group: "Actions", name: "Database scan button" },
  { id: 59, group: "Actions", name: "Project search button" },
  { id: 60, group: "Actions", name: "Web research button" },
  { id: 61, group: "Actions", name: "Image generate button" },
  { id: 62, group: "Actions", name: "File generate button" },
  { id: 63, group: "Reports", name: "Report generate button" },
  { id: 64, group: "Export", name: "Export chat as Markdown" },
  { id: 65, group: "Export", name: "Export chat as TXT" },
  { id: 66, group: "Export", name: "Export chat as PDF" },
  { id: 67, group: "Sharing", name: "Share chat link" },
  { id: 68, group: "Security", name: "Private admin-only chats" },
  { id: 69, group: "Security", name: "Role-based access" },
  { id: 70, group: "Security", name: "Owner-only settings" },
  { id: 71, group: "Memory", name: "Chat history synced to Supabase" },
  { id: 72, group: "Storage", name: "Generated files saved to storage" },
  { id: 73, group: "Storage", name: "Generated images saved to storage" },
  { id: 74, group: "Knowledge", name: "Knowledge base upload" },
  { id: 75, group: "Knowledge", name: "Knowledge search" },
  { id: 76, group: "Knowledge", name: "Repo file index" },
  { id: 77, group: "Knowledge", name: "Supabase schema index" },
  { id: 78, group: "Knowledge", name: "Admin data index" },
  { id: 79, group: "Knowledge", name: "Minecraft server knowledge index" },
  { id: 80, group: "Trust", name: "Tool result citations hidden by default" },
  { id: 81, group: "Trust", name: "Optional source view" },
  { id: 82, group: "Trust", name: "Better hallucination guard" },
  { id: 83, group: "Trust", name: "I don't know fallback" },
  { id: 84, group: "Trust", name: "Clarifying question mode" },
  { id: 85, group: "Modes", name: "Code assistant mode" },
  { id: 86, group: "Modes", name: "Data analyst mode" },
  { id: 87, group: "Modes", name: "Minecraft admin mode" },
  { id: 88, group: "Modes", name: "Store manager mode" },
  { id: 89, group: "Modes", name: "Security auditor mode" },
  { id: 90, group: "Modes", name: "Debugger mode" },
  { id: 91, group: "Modes", name: "Task planner mode" },
  { id: 92, group: "Modes", name: "Report writer mode" },
  { id: 93, group: "Modes", name: "SQL assistant mode" },
  { id: 94, group: "Modes", name: "Product builder mode" },
  { id: 95, group: "Minecraft", name: "RCON command assistant" },
  { id: 96, group: "Minecraft", name: "Live server status tool" },
  { id: 97, group: "Minecraft", name: "Live player list tool" },
  { id: 98, group: "Store", name: "Checkout troubleshooting tool" },
  { id: 99, group: "Store", name: "Order investigation tool" },
  { id: 100, group: "Cloudflare", name: "Cloudflare deploy debugging tool" },
];

export function renderCoreFeatureRegistry() {
  const groups = new Map<string, CoreFeature[]>();
  for (const feature of coreFeatureRegistry) {
    groups.set(feature.group, [...(groups.get(feature.group) || []), feature]);
  }
  return [...groups.entries()]
    .map(([group, features]) => [`${group}`, ...features.map((feature) => `${feature.id}. ${feature.name}`)].join("\n"))
    .join("\n\n");
}
