export type ProjectEntry = {
  path: string;
  kind: string;
  summary: string;
  keywords: string[];
};

export const projectKnowledge = {
  name: "Lunaris Craft websitestore",
  stack: [
    "React 19 + Vite + TypeScript",
    "TanStack Router file routes",
    "Tailwind CSS utility styling",
    "Supabase Auth, Postgres, REST, and Edge Functions",
    "Cloudflare Pages static deployment",
    "PWA manifest/service worker for installable website behavior",
  ],
  architecture:
    "The public store renders shop pages for ranks, keys, bundles, checkout, account, and order status. The existing admin panel is mounted through AdminLegacyRoute and AdminPanel. Supabase helpers in src/lib/supabase.ts handle orders, accounts, promo codes, products, and admin Edge Function calls. The admin-manage-order Edge Function handles privileged actions such as delivery, account sync/delete, and RCON commands when configured.",
  safety:
    "Lunaris Core is a frontend-only tool assistant. It uses a safe static project map and existing Supabase frontend helpers. It must not read .env files, private tokens, service role keys, or raw secrets.",
};

export const projectIndex: ProjectEntry[] = [
  {
    path: "README.md",
    kind: "docs",
    summary: "Project setup notes, Supabase owner setup, environment variable guidance, and Lunaris Core explanation.",
    keywords: ["readme", "docs", "setup", "supabase", "owner", "lunaris core", "environment"],
  },
  {
    path: ".env.example",
    kind: "config",
    summary: "Safe public environment variable template. Only frontend Supabase URL and anon key belong here.",
    keywords: ["env", "environment", "supabase", "anon", "vite"],
  },
  {
    path: "vite.config.ts",
    kind: "config",
    summary: "Vite build configuration with React/TanStack tooling and path aliases.",
    keywords: ["vite", "build", "config", "react", "alias"],
  },
  {
    path: "wrangler.toml",
    kind: "cloudflare",
    summary: "Cloudflare Pages configuration, including output directory and compatibility settings.",
    keywords: ["wrangler", "cloudflare", "pages", "deploy", "dist"],
  },
  {
    path: "src/components/admin/AdminPanel.tsx",
    kind: "admin",
    summary: "Main existing admin panel. Handles orders, accounts, account sync, promo management, product management, admin notes, delivery logs, and order actions.",
    keywords: ["admin", "orders", "accounts", "players", "promos", "products", "delivery", "manage accounts", "confirm", "reject", "delete account"],
  },
  {
    path: "src/components/admin/AdminLegacyRoute.tsx",
    kind: "admin",
    summary: "Mounts the existing AdminPanel and the floating Lunaris Core button for current admin routes.",
    keywords: ["admin", "legacy", "lunaris core", "floating button"],
  },
  {
    path: "src/components/admin/AdminShell.tsx",
    kind: "admin",
    summary: "Newer admin shell layout with sidebar navigation and space background, used by modular admin pages.",
    keywords: ["admin shell", "dashboard", "navigation", "space background", "roles"],
  },
  {
    path: "src/components/admin/AdminOverview.tsx",
    kind: "admin",
    summary: "Dashboard overview cards for requests, products, admin logs, and database changes.",
    keywords: ["overview", "dashboard", "stats", "logs", "requests"],
  },
  {
    path: "src/components/admin/AdminCrudPage.tsx",
    kind: "admin",
    summary: "Reusable CRUD page for ranks, crates, keys, bundles, and cosmetics.",
    keywords: ["crud", "ranks", "crates", "keys", "bundles", "cosmetics", "products"],
  },
  {
    path: "src/components/admin/AdminRequestsPage.tsx",
    kind: "admin",
    summary: "Requests list and filters for admin order/request management.",
    keywords: ["requests", "orders", "status", "search", "filter"],
  },
  {
    path: "src/components/admin/AdminRequestDetailPage.tsx",
    kind: "admin",
    summary: "Single request detail view with confirm, reject, complete, and admin note actions.",
    keywords: ["request detail", "confirm", "reject", "complete", "admin note"],
  },
  {
    path: "src/components/admin/AdminAdminsPage.tsx",
    kind: "admin",
    summary: "Admin profile management for owner/admin/staff/viewer roles.",
    keywords: ["admins", "roles", "owner", "staff", "viewer"],
  },
  {
    path: "src/components/admin/AdminSettingsPage.tsx",
    kind: "admin",
    summary: "Website/admin settings management page.",
    keywords: ["settings", "website settings", "admin settings"],
  },
  {
    path: "src/components/admin/AdminLogsPage.tsx",
    kind: "admin",
    summary: "Admin action logs and audit trail page.",
    keywords: ["logs", "audit", "actions", "admin logs"],
  },
  {
    path: "src/components/admin/LunarisCoreButton.tsx",
    kind: "lunaris-core",
    summary: "Floating admin-only Lunaris Core launcher button that opens the dedicated /admin/core chat workspace.",
    keywords: ["lunaris core", "button", "assistant", "admin only", "admin core"],
  },
  {
    path: "src/components/admin/LunarisCoreWorkspace.tsx",
    kind: "lunaris-core",
    summary: "Full-page ChatGPT-style Lunaris Core workspace with chat history, search, modes, saved memory, suggestions, and bottom prompt bar.",
    keywords: ["lunaris core", "workspace", "full page chat", "chatgpt", "memory", "modes", "history"],
  },
  {
    path: "src/components/admin/LunarisCorePanel.tsx",
    kind: "lunaris-core",
    summary: "Legacy floating chat panel UI for Lunaris Core.",
    keywords: ["lunaris core", "chat", "panel", "quick actions", "messages", "legacy"],
  },
  {
    path: "src/components/admin/LunarisCoreMessage.tsx",
    kind: "lunaris-core",
    summary: "Message bubble renderer for admin and Core replies.",
    keywords: ["lunaris core", "message", "chat bubble"],
  },
  {
    path: "src/components/admin/LunarisCoreQuickActions.tsx",
    kind: "lunaris-core",
    summary: "Preset quick action chips for scans, project search, time/date, and calculator questions.",
    keywords: ["lunaris core", "quick actions", "scan", "search"],
  },
  {
    path: "src/lib/supabase.ts",
    kind: "backend-data",
    summary: "Frontend Supabase data layer for orders, accounts, promos, store products, admin actions, and account sync.",
    keywords: ["supabase", "database", "orders", "accounts", "promo_codes", "store_products", "admin-manage-order"],
  },
  {
    path: "src/lib/adminData.ts",
    kind: "backend-data",
    summary: "Admin data helpers for admin profiles, role checks, admin CRUD tables, logs, settings, and requests.",
    keywords: ["admin data", "admin_profiles", "roles", "logs", "settings", "requests"],
  },
  {
    path: "src/lib/supabaseClient.ts",
    kind: "backend-data",
    summary: "Shared Supabase browser client using VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY only.",
    keywords: ["supabase client", "auth", "anon key", "browser"],
  },
  {
    path: "src/lib/account.tsx",
    kind: "frontend-state",
    summary: "Account context/state for customer profile, authentication, selected account, and account-related UI state.",
    keywords: ["account", "auth", "profile", "customer", "selected account"],
  },
  {
    path: "src/lib/cart.tsx",
    kind: "frontend-state",
    summary: "Cart context/state for store items, quantities, cart drawer, checkout totals, and cart actions.",
    keywords: ["cart", "checkout", "items", "total", "quantity"],
  },
  {
    path: "src/lib/order-cache.ts",
    kind: "frontend-state",
    summary: "Local order cache helper for order status flow and recently submitted orders.",
    keywords: ["order cache", "order status", "submitted order"],
  },
  {
    path: "src/routes/checkout.tsx",
    kind: "route",
    summary: "Checkout page. Creates orders, validates account/email state, GCash reference, and records purchases.",
    keywords: ["checkout", "gcash", "submit order", "cart", "payment"],
  },
  {
    path: "src/routes/account.tsx",
    kind: "route",
    summary: "Account page for sign up, sign in, email verification, profile, order history, and password reset.",
    keywords: ["account", "login", "signup", "email", "password reset", "profile"],
  },
  {
    path: "src/routes/order.$orderId.tsx",
    kind: "route",
    summary: "Customer order status page for tracking a submitted order by order ID.",
    keywords: ["order status", "receipt", "tracking", "order id"],
  },
  {
    path: "src/routes/index.tsx",
    kind: "route",
    summary: "Home page with hero, store sections, server join CTA, and featured items.",
    keywords: ["home", "landing", "hero", "featured", "join"],
  },
  {
    path: "src/routes/ranks.tsx",
    kind: "route",
    summary: "Ranks shop page showing rank products and perks.",
    keywords: ["ranks", "shop", "products", "perks"],
  },
  {
    path: "src/routes/keys.tsx",
    kind: "route",
    summary: "Keys shop page. Currently keys can be managed through admin products and shown when active.",
    keywords: ["keys", "crate keys", "shop", "coming soon"],
  },
  {
    path: "src/routes/bundles.tsx",
    kind: "route",
    summary: "Bundles shop page. Bundles can be managed through admin products and shown when active.",
    keywords: ["bundles", "shop", "coming soon"],
  },
  {
    path: "src/routes/admin.tsx",
    kind: "route",
    summary: "Admin base route that serves the existing private admin panel.",
    keywords: ["admin", "/admin", "route"],
  },
  {
    path: "src/routes/admin.dashboard.tsx",
    kind: "route",
    summary: "Admin dashboard route, currently wired into existing admin systems.",
    keywords: ["admin dashboard", "route"],
  },
  {
    path: "src/routes/admin.core.tsx",
    kind: "route",
    summary: "Dedicated full-page Lunaris Core admin AI chat route at /admin/core.",
    keywords: ["admin core", "lunaris core", "route", "ai chat", "chatgpt"],
  },
  {
    path: "src/routes/admin.requests.tsx",
    kind: "route",
    summary: "Admin requests route.",
    keywords: ["admin requests", "route", "orders"],
  },
  {
    path: "src/routes/admin.requests.$id.tsx",
    kind: "route",
    summary: "Admin request detail route.",
    keywords: ["admin request detail", "route", "order id"],
  },
  {
    path: "src/routes/admin.ranks.tsx",
    kind: "route",
    summary: "Admin ranks route.",
    keywords: ["admin ranks", "route", "products"],
  },
  {
    path: "src/routes/admin.keys.tsx",
    kind: "route",
    summary: "Admin keys route.",
    keywords: ["admin keys", "route", "products"],
  },
  {
    path: "src/routes/admin.bundles.tsx",
    kind: "route",
    summary: "Admin bundles route.",
    keywords: ["admin bundles", "route", "products"],
  },
  {
    path: "src/routes/admin.crates.tsx",
    kind: "route",
    summary: "Admin crates route.",
    keywords: ["admin crates", "route", "products"],
  },
  {
    path: "src/routes/admin.cosmetics.tsx",
    kind: "route",
    summary: "Admin cosmetics route.",
    keywords: ["admin cosmetics", "route", "products"],
  },
  {
    path: "src/routes/admin.admins.tsx",
    kind: "route",
    summary: "Admin management route.",
    keywords: ["admin admins", "route", "roles"],
  },
  {
    path: "src/routes/admin.settings.tsx",
    kind: "route",
    summary: "Admin settings route.",
    keywords: ["admin settings", "route"],
  },
  {
    path: "src/routes/admin.logs.tsx",
    kind: "route",
    summary: "Admin logs route.",
    keywords: ["admin logs", "route", "audit"],
  },
  {
    path: "src/routes/admin.login.tsx",
    kind: "route",
    summary: "Admin login/access route.",
    keywords: ["admin login", "route", "auth"],
  },
  {
    path: "src/lib/products.ts",
    kind: "store",
    summary: "Product fallbacks and product loading/merge logic for ranks, keys, and bundles.",
    keywords: ["ranks", "keys", "bundles", "products", "prices", "perks"],
  },
  {
    path: "src/components/ProductGrid.tsx",
    kind: "frontend",
    summary: "Reusable public product grid/cards for ranks, keys, and bundles.",
    keywords: ["product grid", "cards", "ranks", "keys", "bundles"],
  },
  {
    path: "src/components/CartDrawer.tsx",
    kind: "frontend",
    summary: "Floating cart drawer, cart item list, subtotal, and checkout link.",
    keywords: ["cart drawer", "checkout", "cart", "subtotal"],
  },
  {
    path: "src/components/Navbar.tsx",
    kind: "frontend",
    summary: "Public top navigation with logo, shop links, account, Discord, and cart.",
    keywords: ["navbar", "logo", "navigation", "cart", "account"],
  },
  {
    path: "src/components/SiteFooter.tsx",
    kind: "frontend",
    summary: "Footer with server/store links and copyright.",
    keywords: ["footer", "copyright", "links"],
  },
  {
    path: "src/components/JoinCTA.tsx",
    kind: "frontend",
    summary: "Join server call-to-action with server address and port display/copy actions.",
    keywords: ["join", "server ip", "port", "copy", "minecraft"],
  },
  {
    path: "src/components/Starfield.tsx",
    kind: "frontend",
    summary: "Animated space/star background used across the Lunaris theme.",
    keywords: ["starfield", "background", "stars", "animation"],
  },
  {
    path: "src/styles.css",
    kind: "frontend",
    summary: "Global Tailwind/imported styles, theme variables, animations, and visual polish.",
    keywords: ["css", "styles", "tailwind", "theme", "animation"],
  },
  {
    path: "src/lib/promos.ts",
    kind: "store",
    summary: "Promo code calculation helpers and promo rule validation.",
    keywords: ["promo", "discount", "coupon", "percent", "fixed"],
  },
  {
    path: "src/lib/lunarisCore/intentDetector.ts",
    kind: "lunaris-core",
    summary: "Detects whether an admin message is about greetings, tools, project files, database scans, time/date, calculator, build/deploy, or research.",
    keywords: ["lunaris core", "intent", "classify", "detect"],
  },
  {
    path: "src/lib/lunarisCore/toolRouter.ts",
    kind: "lunaris-core",
    summary: "Routes detected intents to the right built-in Core tool.",
    keywords: ["lunaris core", "router", "tools"],
  },
  {
    path: "src/lib/lunarisCore/databaseScanner.ts",
    kind: "lunaris-core",
    summary: "Scans existing Supabase data through safe frontend helpers for orders, accounts, promos, and products.",
    keywords: ["lunaris core", "database scanner", "orders", "accounts", "promos", "products"],
  },
  {
    path: "src/lib/lunarisCore/projectIndexer.ts",
    kind: "lunaris-core",
    summary: "Static safe knowledge map of frontend, backend, admin, Supabase, Cloudflare, and Core files.",
    keywords: ["lunaris core", "project index", "knowledge", "files"],
  },
  {
    path: "src/lib/lunarisCore/projectSearch.ts",
    kind: "lunaris-core",
    summary: "Searches the safe project index and exposes project overview helpers.",
    keywords: ["lunaris core", "project search", "find files"],
  },
  {
    path: "src/lib/lunarisCore/providerAdapter.ts",
    kind: "lunaris-core",
    summary: "Cloudflare Workers AI adapter. Sends grounded local Core context to the private Pages Function when the admin has a valid Supabase session.",
    keywords: ["lunaris core", "provider", "cloudflare ai", "workers ai", "pages function", "model"],
  },
  {
    path: "functions/api/lunaris-core/chat.ts",
    kind: "backend",
    summary: "Cloudflare Pages Function that verifies the admin Supabase session, calls the Workers AI binding, and returns model-generated Lunaris Core answers.",
    keywords: ["lunaris core", "cloudflare ai", "workers ai", "pages function", "api", "model", "admin auth"],
  },
  {
    path: "src/lib/store-config.ts",
    kind: "config",
    summary: "Store-wide settings including Discord link, GCash details, server host, and port.",
    keywords: ["config", "gcash", "discord", "server ip", "port"],
  },
  {
    path: "supabase/migrations/20260626092022_create_orders_table.sql",
    kind: "database",
    summary: "Initial orders table schema for checkout/order storage.",
    keywords: ["supabase", "migration", "orders", "schema"],
  },
  {
    path: "supabase/migrations/20260628000000_add_checkout_promos.sql",
    kind: "database",
    summary: "Checkout promo-code schema additions.",
    keywords: ["supabase", "migration", "promos", "promo_codes", "discount"],
  },
  {
    path: "supabase/migrations/20260628001000_create_accounts_table.sql",
    kind: "database",
    summary: "Accounts table schema for customer/player accounts.",
    keywords: ["supabase", "migration", "accounts", "players", "schema"],
  },
  {
    path: "supabase/migrations/20260630000000_lunaris_admin_assistant.sql",
    kind: "database",
    summary: "Admin/store foundation migration for admin profiles, ranks, crates, keys, bundles, cosmetics, requests, settings, logs, and old assistant tables.",
    keywords: ["supabase", "migration", "admin_profiles", "ranks", "crates", "crate_keys", "bundles", "cosmetics", "requests", "admin_logs", "settings"],
  },
  {
    path: "src/routes/__root.tsx",
    kind: "route",
    summary: "Root app shell, cart drawer gate, route outlet, error handling, and app metadata.",
    keywords: ["root", "routes", "error", "cart", "metadata"],
  },
  {
    path: "src/router.tsx",
    kind: "route",
    summary: "TanStack Router setup using the generated route tree.",
    keywords: ["router", "tanstack", "routes"],
  },
  {
    path: "src/routeTree.gen.ts",
    kind: "route",
    summary: "Generated route tree from file-based routes. Do not hand edit unless debugging generated route output.",
    keywords: ["route tree", "generated", "tanstack"],
  },
  {
    path: "package.json",
    kind: "config",
    summary: "Project scripts and dependencies for Vite, React, TanStack Router, Supabase, Tailwind, and build.",
    keywords: ["package", "build", "vite", "dependencies", "pnpm"],
  },
  {
    path: "pnpm-lock.yaml",
    kind: "config",
    summary: "Dependency lockfile for reproducible Cloudflare/local builds.",
    keywords: ["pnpm", "lockfile", "dependencies", "cloudflare"],
  },
  {
    path: "pnpm-workspace.yaml",
    kind: "config",
    summary: "Workspace config. Current app only uses the root package.",
    keywords: ["pnpm", "workspace", "config"],
  },
  {
    path: "tsconfig.json",
    kind: "config",
    summary: "TypeScript compiler configuration.",
    keywords: ["typescript", "tsconfig", "config"],
  },
  {
    path: "eslint.config.js",
    kind: "config",
    summary: "ESLint configuration for code quality checks.",
    keywords: ["eslint", "lint", "config"],
  },
  {
    path: "public/_redirects",
    kind: "cloudflare",
    summary: "Cloudflare Pages routing rules for SPA/direct routes.",
    keywords: ["cloudflare", "redirects", "routing", "spa"],
  },
  {
    path: "public/_headers",
    kind: "cloudflare",
    summary: "Cloudflare Pages headers and cache settings.",
    keywords: ["cloudflare", "headers", "cache"],
  },
  {
    path: "public/manifest.webmanifest",
    kind: "pwa",
    summary: "PWA manifest for app name, icons, theme color, display mode, and install behavior.",
    keywords: ["pwa", "manifest", "iphone", "install", "icon"],
  },
  {
    path: "public/sw.js",
    kind: "pwa",
    summary: "Service worker file for PWA behavior/cache hooks.",
    keywords: ["service worker", "pwa", "cache"],
  },
  {
    path: "public/lunaris.logo.png",
    kind: "asset",
    summary: "Public Lunaris Craft logo image used by the website.",
    keywords: ["logo", "lunaris", "image", "asset"],
  },
  {
    path: "public/gcash-qr.webp",
    kind: "asset",
    summary: "Public GCash QR code image used in checkout/payment instructions.",
    keywords: ["gcash", "qr", "payment", "asset"],
  },
  {
    path: "supabase/functions/admin-manage-order/index.ts",
    kind: "backend",
    summary: "Supabase Edge Function for admin order management, account sync/delete, and RCON delivery if deployed. Uses server-side secrets configured in Supabase.",
    keywords: ["function", "rcon", "delivery", "sync accounts", "delete account", "service role", "edge function"],
  },
];
