/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/keys': typeof KeysRoute
  '/ranks': typeof RanksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/keys': typeof KeysRoute
  '/ranks': typeof RanksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/keys': typeof KeysRoute
  '/ranks': typeof RanksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/account' | '/admin' | '/bundles' | '/checkout' | '/keys' | '/ranks'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/account' | '/admin' | '/bundles' | '/checkout' | '/keys' | '/ranks'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/bundles'
    | '/checkout'
    | '/keys'
    | '/ranks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BundlesRoute: typeof BundlesRoute
  CheckoutRoute: typeof CheckoutRoute
  KeysRoute: typeof KeysRoute
  RanksRoute: typeof RanksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BundlesRoute: BundlesRoute,
  CheckoutRoute: CheckoutRoute,
  KeysRoute: KeysRoute,
  RanksRoute: RanksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
