/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminRanksRouteImport } from './routes/admin.ranks'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminKeysRouteImport } from './routes/admin.keys'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCratesRouteImport } from './routes/admin.crates'
import { Route as AdminCosmeticsRouteImport } from './routes/admin.cosmetics'
import { Route as AdminBundlesRouteImport } from './routes/admin.bundles'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'

const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRanksRoute = AdminRanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCratesRoute = AdminCratesRouteImport.update({
  id: '/crates',
  path: '/crates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCosmeticsRoute = AdminCosmeticsRouteImport.update({
  id: '/cosmetics',
  path: '/cosmetics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBundlesRoute = AdminBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/keys': typeof KeysRoute
  '/ranks': typeof RanksRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/cosmetics': typeof AdminCosmeticsRoute
  '/admin/crates': typeof AdminCratesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/ranks': typeof AdminRanksRoute
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/keys': typeof KeysRoute
  '/ranks': typeof RanksRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/cosmetics': typeof AdminCosmeticsRoute
  '/admin/crates': typeof AdminCratesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/ranks': typeof AdminRanksRoute
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/keys': typeof KeysRoute
  '/ranks': typeof RanksRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/cosmetics': typeof AdminCosmeticsRoute
  '/admin/crates': typeof AdminCratesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/ranks': typeof AdminRanksRoute
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/bundles'
    | '/checkout'
    | '/keys'
    | '/ranks'
    | '/admin/admins'
    | '/admin/bundles'
    | '/admin/cosmetics'
    | '/admin/crates'
    | '/admin/dashboard'
    | '/admin/keys'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/ranks'
    | '/admin/requests'
    | '/admin/settings'
    | '/order/$orderId'
    | '/admin/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/bundles'
    | '/checkout'
    | '/keys'
    | '/ranks'
    | '/admin/admins'
    | '/admin/bundles'
    | '/admin/cosmetics'
    | '/admin/crates'
    | '/admin/dashboard'
    | '/admin/keys'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/ranks'
    | '/admin/requests'
    | '/admin/settings'
    | '/order/$orderId'
    | '/admin/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/bundles'
    | '/checkout'
    | '/keys'
    | '/ranks'
    | '/admin/admins'
    | '/admin/bundles'
    | '/admin/cosmetics'
    | '/admin/crates'
    | '/admin/dashboard'
    | '/admin/keys'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/ranks'
    | '/admin/requests'
    | '/admin/settings'
    | '/order/$orderId'
    | '/admin/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BundlesRoute: typeof BundlesRoute
  CheckoutRoute: typeof CheckoutRoute
  KeysRoute: typeof KeysRoute
  RanksRoute: typeof RanksRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ranks': {
      id: '/admin/ranks'
      path: '/ranks'
      fullPath: '/admin/ranks'
      preLoaderRoute: typeof AdminRanksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crates': {
      id: '/admin/crates'
      path: '/crates'
      fullPath: '/admin/crates'
      preLoaderRoute: typeof AdminCratesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cosmetics': {
      id: '/admin/cosmetics'
      path: '/cosmetics'
      fullPath: '/admin/cosmetics'
      preLoaderRoute: typeof AdminCosmeticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bundles': {
      id: '/admin/bundles'
      path: '/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AdminBundlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof AdminRequestsRoute
    }
  }
}

interface AdminRequestsRouteChildren {
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
}

const AdminRequestsRouteChildren: AdminRequestsRouteChildren = {
  AdminRequestsIdRoute: AdminRequestsIdRoute,
}

const AdminRequestsRouteWithChildren = AdminRequestsRoute._addFileChildren(
  AdminRequestsRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminBundlesRoute: typeof AdminBundlesRoute
  AdminCosmeticsRoute: typeof AdminCosmeticsRoute
  AdminCratesRoute: typeof AdminCratesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminRanksRoute: typeof AdminRanksRoute
  AdminRequestsRoute: typeof AdminRequestsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminBundlesRoute: AdminBundlesRoute,
  AdminCosmeticsRoute: AdminCosmeticsRoute,
  AdminCratesRoute: AdminCratesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminRanksRoute: AdminRanksRoute,
  AdminRequestsRoute: AdminRequestsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BundlesRoute: BundlesRoute,
  CheckoutRoute: CheckoutRoute,
  KeysRoute: KeysRoute,
  RanksRoute: RanksRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
